version: '3'
services:
  download-stream-main:
    image: resilio-sync-main
    build: ./local/resilio-sync-main
    volumes:
      - ${CONFIG_DIR}:/app/config
      - ${RESILIO_SYNC_DIR}:/resilio-sync
    ports:
      - 8888:8888
